version: "3.7"
services:
  front:
    build: ./front
    environment:
      - "API_PUBLIC_BASE_URL=http://localhost:80"
    ports:
      - "80:80"
  api:
    build: ./api
    links:
      - "db"
    environment:
      - "DB_HOST=db"
  db:
    image: postgres:12-alpine
    environment:
      - "POSTGRES_PASSWORD=fishNShips123"

